### ISSUE TITLE
dornhofers textdatei fehlerhaft

### ISSUE THREAD

**Issue by ManfredSteiner** [HTLMechatronics/m12#1]
@dorjom12 Da scheint was schief gegangen zu sein.

**Bitte prüfen**: [dorjom12.txt](dorjom12.txt)

**Comment by dorjom12** [comment]
Link funktioniert nicht

**Comment by ManfredSteiner** [comment]
@dorjom12, Sorry, hier der richtige Link:
[dorjom12.txt](https://github.com/HTLMechatronics/m12/blob/master/dorjom12.txt)

**Comment by dorjom12** [comment]
Problem gelöst
